name: My Workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Hello World
      run: |
        echo "Hello, world!"
        echo "This is a simple GitHub Actions workflow."

  list-contents:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Print current working directory
      run: pwd

    - name: Check script.sh existence
      run: ls -al .github/workflows/script.sh

    - name: Set execute permission on script.sh
      run: chmod +x .github/workflows/script.sh

    - name: Run script.sh with full path
      run: ./.github/workflows/script.sh
