name: My Workflow
on: 
  push:  
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: Print current working directory
        run: pwd
      
      - name: Set execute permission on script.sh
        run: chmod +x script.sh

      - name: Run script.sh
        run: script.sh
