name: My Workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Hello World
      run: |
        echo "Hello, world!"
        echo "This is a simple GitHub Actions workflow."

  list-contents:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: List current directory contents
      run: ls -al
